import { useEffect, useState } from "react";
import { Check, RefreshCw, ShieldCheck } from "lucide-react";
import { createCommercialCheckout, getCommercialPlans, getCommercialStatus, refreshCommercialEntitlement, type CommercialPlan, type CommercialStatus } from "../../infrastructure/commercial";
import { toUserMessage } from "../../domain/errors";

const fallbackPlans:CommercialPlan[]=[
  {code:"ESSENTIAL_MONTHLY",name:"Caixa no Controle Essencial",billingCycle:"MONTHLY",amountCents:990,offlineLeaseDays:7,gracePeriodDays:5},
  {code:"ESSENTIAL_ANNUAL",name:"Caixa no Controle Essencial",billingCycle:"ANNUAL",amountCents:9990,offlineLeaseDays:30,gracePeriodDays:10},
];
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const states:Record<string,string>={TRIAL:"Teste gratuito",PAYMENT_PENDING:"Aguardando confirmação do pagamento",ACTIVE:"Assinatura ativa",GRACE_PERIOD:"Período de tolerância",PAYMENT_FAILED:"Pagamento não aprovado",EXPIRED:"Assinatura expirada",CANCELED:"Assinatura cancelada",REFUNDED:"Pagamento estornado",REVALIDATION_REQUIRED:"Validação online necessária"};

export function SubscriptionPanel({defaultName=""}:{defaultName?:string}){
  const [plans,setPlans]=useState(fallbackPlans);const [selected,setSelected]=useState<CommercialPlan["code"]>("ESSENTIAL_ANNUAL");const [name,setName]=useState(defaultName);const [email,setEmail]=useState("");const [document,setDocument]=useState("");const [status,setStatus]=useState<CommercialStatus|null>(null);const [busy,setBusy]=useState(false);const [feedback,setFeedback]=useState("");
  useEffect(()=>setName(value=>value||defaultName),[defaultName]);
  useEffect(()=>{if(!("__TAURI_INTERNALS__" in window))return;void Promise.all([getCommercialPlans(),getCommercialStatus()]).then(([available,current])=>{setPlans(available);setStatus(current)}).catch(()=>undefined)},[]);
  const checkout=async()=>{if(name.trim().length<2||!/^\S+@\S+\.\S+$/.test(email)){setFeedback("Informe seu nome e um e-mail válido para continuar.");return}setBusy(true);setFeedback("");try{await createCommercialCheckout({name:name.trim(),email:email.trim(),document:document.trim()||null,planCode:selected});setFeedback("Checkout aberto no navegador. Após o pagamento, volte aqui e clique em Verificar pagamento.");setStatus(await getCommercialStatus())}catch(error){setFeedback(toUserMessage(error))}finally{setBusy(false)}};
  const refresh=async()=>{setBusy(true);setFeedback("");try{const current=await refreshCommercialEntitlement();setStatus(current);setFeedback(current.state==="ACTIVE"?"Pagamento confirmado e assinatura ativada.":states[current.state]??"Situação atualizada.");window.dispatchEvent(new Event("cnc-entitlement-changed"))}catch(error){setFeedback(toUserMessage(error))}finally{setBusy(false)}};
  return <section aria-labelledby="subscription-title" className="rounded-xl border border-slate-200 bg-white p-5 shadow-surface">
    <div className="flex items-start gap-3"><ShieldCheck className="mt-1 text-brand" aria-hidden="true"/><div><h2 id="subscription-title" className="text-lg font-bold text-ink">Meu plano</h2><p className="mt-1 text-sm text-slate-600">Pagamento seguro no ambiente do Mercado Pago. O aplicativo não solicita nem armazena dados do cartão.</p></div></div>
    {status&&<div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><strong>{states[status.state]??status.state}</strong>{status.validUntil&&<span className="block text-slate-600">Uso offline autorizado até {new Date(status.validUntil).toLocaleString("pt-BR")}.</span>}{status.requiresOnlineValidation&&<span className="block font-medium text-amber-700">Conecte-se para renovar a autorização.</span>}</div>}
    <div className="mt-4 grid gap-3 sm:grid-cols-2">{plans.map(plan=><button type="button" key={plan.code} onClick={()=>setSelected(plan.code)} aria-pressed={selected===plan.code} className={`relative rounded-xl border p-4 text-left ${selected===plan.code?"border-brand bg-blue-50 ring-2 ring-blue-100":"border-slate-200"}`}>{plan.code==="ESSENTIAL_ANNUAL"&&<span className="absolute right-3 top-3 rounded-full bg-positive px-2 py-1 text-xs font-bold text-white">Mais vantajoso</span>}<span className="block font-bold text-ink">{plan.billingCycle==="MONTHLY"?"Mensal":"Anual"}</span><span className="mt-2 block text-2xl font-black text-ink">{money.format(plan.amountCents/100)}</span><span className="text-xs text-slate-600">{plan.billingCycle==="MONTHLY"?"por mês":"por ano"} · até {plan.offlineLeaseDays} dias offline</span><span className="mt-3 flex items-center gap-1 text-xs text-slate-600"><Check size={14}/>Todos os recursos Essenciais</span></button>)}</div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Nome<input value={name} onChange={e=>setName(e.target.value)} maxLength={120} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="text-sm font-semibold text-slate-700">E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 px-3 font-normal"/></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">CPF/CNPJ (opcional)<input value={document} onChange={e=>setDocument(e.target.value)} maxLength={32} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 px-3 font-normal"/></label></div>
    <div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={()=>void checkout()} className="min-h-11 rounded-lg bg-brand px-4 py-2 font-semibold text-white disabled:opacity-60">Assinar no Mercado Pago</button>{status?.subscriptionId&&<button type="button" disabled={busy} onClick={()=>void refresh()} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-slate-300 px-4 py-2 font-semibold"><RefreshCw size={16}/>Verificar pagamento</button>}</div>
    {feedback&&<p role="status" className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{feedback}</p>}
  </section>
}
