import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import test from "node:test";
import type { Config } from "../src/config.js";
import { MercadoPagoProvider } from "../src/mercado-pago-provider.js";

const config:Config={NODE_ENV:"test",HOST:"127.0.0.1",PORT:8080,DATABASE_URL:"postgres://test",DATABASE_SSL_MODE:"disable",COMMERCIAL_PUBLIC_URL:"https://commercial.example.com",MERCADO_PAGO_ACCESS_TOKEN:"APP_USR_token-servidor-teste",MERCADO_PAGO_WEBHOOK_SECRET:"segredo-webhook-teste",MERCADO_PAGO_MONTHLY_PLAN_ID:"monthly",MERCADO_PAGO_ANNUAL_PLAN_ID:"annual",ENTITLEMENT_PRIVATE_KEY_PATH:"unused",ENTITLEMENT_KEY_ID:"test-key",ALLOWED_APP_ORIGIN:"https://app.example.com",COMMERCIAL_ENVIRONMENT:"sandbox"};

test("checkout pendente envia recorrência e não exige token de cartão",async()=>{let body:Record<string,unknown>={};const original=globalThis.fetch;globalThis.fetch=async(_input,init)=>{body=JSON.parse(String(init?.body));return Response.json({id:"subscription-1",init_point:"https://www.mercadopago.com.br/subscriptions/checkout?preapproval_id=subscription-1"})};try{const provider=new MercadoPagoProvider(config);const result=await provider.createSubscription({subscriptionId:"11111111-1111-4111-8111-111111111111",customerEmail:"comprador@testuser.com",installationCode:"CNC-ABCD-EFGH-IJKL",plan:{code:"ESSENTIAL_ANNUAL",name:"Caixa no Controle Essencial",billingCycle:"ANNUAL",amountCents:9990,edition:"ESSENTIAL",offlineLeaseDays:30,gracePeriodDays:10}});assert.equal(result.providerSubscriptionId,"subscription-1");assert.equal(body.preapproval_plan_id,undefined);assert.equal(body.status,"pending");assert.deepEqual(body.auto_recurring,{frequency:12,frequency_type:"months",transaction_amount:99.9,currency_id:"BRL"})}finally{globalThis.fetch=original}});

test("webhook inválido é recusado antes de consultar o provedor",async()=>{let calls=0;const original=globalThis.fetch;globalThis.fetch=async()=>{calls++;return new Response("{}")};try{const provider=new MercadoPagoProvider(config,()=>new Date("2026-08-07T12:00:00Z"));await assert.rejects(()=>provider.processWebhook({xSignature:"ts=1786104000,v1="+"0".repeat(64),xRequestId:"request-1",dataId:"123",body:{type:"subscription_preapproval",id:"event-1"}}),/inválida/);assert.equal(calls,0)}finally{globalThis.fetch=original}});

test("webhook assinado consulta o recurso integral no Mercado Pago",async()=>{let requested="";const original=globalThis.fetch;globalThis.fetch=async(input)=>{requested=String(input);return Response.json({id:"123",external_reference:"11111111-1111-4111-8111-111111111111",status:"authorized",next_payment_date:"2026-09-07T12:00:00Z",auto_recurring:{transaction_amount:9.9}})};try{const timestamp="1786104000";const requestId="request-2";const manifest=`id:123;request-id:${requestId};ts:${timestamp};`;const signature=createHmac("sha256",config.MERCADO_PAGO_WEBHOOK_SECRET).update(manifest).digest("hex");const provider=new MercadoPagoProvider(config,()=>new Date("2026-08-07T12:00:00Z"));const snapshot=await provider.processWebhook({xSignature:`ts=${timestamp},v1=${signature}`,xRequestId:requestId,dataId:"123",body:{type:"subscription_preapproval",id:"event-2"}});assert.equal(requested,"https://api.mercadopago.com/preapproval/123");assert.equal(snapshot.status,"ACTIVE");assert.equal(snapshot.amountCents,990)}finally{globalThis.fetch=original}});

test("webhook de pagamento vincula assinatura no formato atual do Mercado Pago",async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({id:173061154454,external_reference:"11111111-1111-4111-8111-111111111111",status:"approved",transaction_amount:9.9,date_approved:"2026-08-10T17:10:22Z",point_of_interaction:{transaction_data:{subscription_id:"subscription-1"}}});try{const timestamp="1786381822";const requestId="request-payment";const manifest=`id:173061154454;request-id:${requestId};ts:${timestamp};`;const signature=createHmac("sha256",config.MERCADO_PAGO_WEBHOOK_SECRET).update(manifest).digest("hex");const provider=new MercadoPagoProvider(config,()=>new Date("2026-08-10T17:10:22Z"));const snapshot=await provider.processWebhook({xSignature:`ts=${timestamp},v1=${signature}`,xRequestId:requestId,dataId:"173061154454",body:{type:"payment",id:"event-payment"}});assert.equal(snapshot.providerSubscriptionId,"subscription-1");assert.equal(snapshot.status,"ACTIVE");assert.equal(snapshot.amountCents,990);assert.equal(snapshot.providerPaymentId,"173061154454")}finally{globalThis.fetch=original}});

test("webhooks assinados traduzem recusa, reembolso e chargeback",async()=>{const cases=[{provider:"rejected",expected:"PAYMENT_FAILED"},{provider:"refunded",expected:"REFUNDED"},{provider:"charged_back",expected:"REFUNDED"}] as const;const original=globalThis.fetch;try{for(const [index,item] of cases.entries()){globalThis.fetch=async()=>Response.json({id:9000+index,external_reference:"11111111-1111-4111-8111-111111111111",status:item.provider,transaction_amount:9.9,date_approved:"2026-08-10T17:10:22Z",point_of_interaction:{transaction_data:{subscription_id:"subscription-1"}}});const timestamp="1786381822";const requestId=`request-status-${index}`;const dataId=String(9000+index);const manifest=`id:${dataId};request-id:${requestId};ts:${timestamp};`;const signature=createHmac("sha256",config.MERCADO_PAGO_WEBHOOK_SECRET).update(manifest).digest("hex");const provider=new MercadoPagoProvider(config,()=>new Date("2026-08-10T17:10:22Z"));const snapshot=await provider.processWebhook({xSignature:`ts=${timestamp},v1=${signature}`,xRequestId:requestId,dataId,body:{type:"payment",id:`event-${item.provider}`}});assert.equal(snapshot.status,item.expected)}}finally{globalThis.fetch=original}});
